Toloka/crowd-kit

.github/workflows/tests.yml, src/aggregation/dawid_skene.py, tests/aggregation/test_ds_aggregation.py
Fixes issue https://github.com/Toloka/crowd-kit/issues/6
=> Fix Dawid-Skene issue with integer column names

src/aggregation/__init__.pyi, src/aggregation/bradley_terry.pyi, src/aggregation/closest_to_average.py, src/aggregation/closest_to_average.pyi, src/aggregation/noisy_bt.pyi
* Fixed docsting issue https://github.com/Toloka/crowd-kit/issues/3
* Updated stub-files
=> Fix docstring issue

.github/workflows/tests.yml, README.md, setup.cfg
This is a simple PR that adds a nice documentation badge and runs `build` on GitHub Actions every time we run the tests.
=> Add documentation badge and build the package during testing

README.md
Add new methods to readme.
Just added two lines in readme
=> Add One-coin DS and KOS to README.md

README.md
This pull request makes `README.md` nicer. It adds the missing language model-based textual aggregation method.
=> Add header and LM-based aggregation item

crowdkit/aggregation/classification/dawid_skene.py, crowdkit/aggregation/classification/glad.py, crowdkit/aggregation/embeddings/hrrasa.py, tests/postprocessing/test_entropy_threshold.py
Fix the warnings in the tests as follows:
- Replace DataFrame.append with pandas.concat (append is deprecated);
- Make a copy of DataFrame before assigning;
- Explicitly create an empty Series and specify dtype when the Series is None;
- Catch the user warning when it's intended.
=> Fix the warnings in tests

tests/aggregation/test_bt_aggregation.py
Catch overflow warnings from noisy bradley terry algorithm while we are not using autograd.
=> Catch overflow warnings from noisy BT

README.md, crowdkit/aggregation/__init__.py, crowdkit/aggregation/classification/__init__.py, crowdkit/aggregation/classification/mace.py, tests/aggregation/test_mace_aggregation.py
I have added the MACE aggregation model.
https://www.cs.cmu.edu/~hovy/papers/13HLT-MACE.pdf
Based on the original VB inference implementation, I wrote it in Python.
https://github.com/Toloka/crowd-kit/issues/5
=> Add MACE aggregation model

crowdkit/aggregation/classification/majority_vote.py, crowdkit/aggregation/image_segmentation/segmentation_majority_vote.py, crowdkit/aggregation/utils.py
In `add_skills_to_data()` the empty values of `default_skill` are handled, so we can make it optional.
=> Accept optional default_skill in add_skills_to_data()

crowdkit/__init__.py
=> Bump version to 1.1.0.rc1

crowdkit/__init__.py
=> Bump version to 1.1.0.rc3

.github/PULL_REQUEST_TEMPLATE.md, crowdkit/__init__.py
=> Bump version to 1.1.0.rc4

crowdkit/aggregation/classification/glad.py, crowdkit/aggregation/classification/mace.py, crowdkit/aggregation/embeddings/hrrasa.py, crowdkit/metrics/data/_classification.py
This pull request removes 1410 FutureWarnings caused by pandas. I saved current behavior, therefore, code works the same way
=> Fix pandas warnings

README.md
Solves https://github.com/Toloka/crowd-kit/issues/48
=> Add `learning` to readme

crowdkit/aggregation/embeddings/closest_to_average.py, crowdkit/aggregation/embeddings/hrrasa.py, crowdkit/aggregation/embeddings/rasa.py
Updated the Embeddings section:
- added extra information to the models descriptions;
- added descriptions for parameters;
- fixed errors and typos in descriptions.
=> Documentation updates for Embeddings

docs/en/_includes/crowd-kit-reference-toc.yaml
Updated the menu for the documentation to make several pages visible
=> Updated menu for documenation

crowdkit/aggregation/classification/dawid_skene.py, crowdkit/aggregation/multilabel/binary_relevance.py, crowdkit/learning/conal.py, tests/aggregation/test_binary_relevance_aggregation.py, tests/learning/test_conal.py
I fixed the warnings in the tests. More specifically, I fixed FutureWarnings for pandas and PyTorch and I added filters for the warnings that cannot be fixed. I am not sure if it's correct to filter them – so looking forward for your comments.
=> Fix warnings in the tests

Pipfile
Use the standard Pipfile syntax for dependencies instead of adding the ZIP archive.
=> Simplify Pipfile

crowdkit/aggregation/texts/text_hrrasa.py, crowdkit/aggregation/texts/text_rasa.py
=> Fix RASA & HRRASA

CHANGELOG.md, crowdkit/__init__.py, examples/Readability-Pairwise.ipynb, examples/TlkAgg-Categorical.ipynb
=> Bump version to 1.2.1

Pipfile, setup.cfg
Instead of defining dependencies in `Pipfile`, we define everything in `setup.cfg`.
=> Define all dependencies in one place

.github/workflows/tests.yml
As we don't run all the Jupyter notebooks during tests anymore, this PR adds basic syntax checks for them during tests.
=> Add syntax checks for notebooks

examples/Image-Segmentation.ipynb
- [x ] I have read the **CONTRIBUTING** document
- [x ] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
=> New example for Image-Segmentation

crowdkit/aggregation/classification/majority_vote.py, crowdkit/aggregation/image_segmentation/segmentation_em.py, crowdkit/aggregation/image_segmentation/segmentation_majority_vote.py, crowdkit/aggregation/image_segmentation/segmentation_rasa.py
Updated the Image segmentation section:
- added extra information to the models descriptions;
- added descriptions for parameters;
- fixed errors and typos in descriptions.
=> updated docs for Image Segmentation section

crowdkit/aggregation/classification/majority_vote.py
=> Fixed:weighted majority vote example:use instance rather than class

crowdkit/datasets/_base.py, crowdkit/datasets/_loaders.py
=> fix: tiny typo

crowdkit/aggregation/classification/dawid_skene.py, tests/aggregation/test_ds_aggregation.py
=> add: ds support golden question

crowdkit/aggregation/classification/dawid_skene.py, crowdkit/aggregation/classification/gold_majority_vote.py, crowdkit/aggregation/classification/kos.py, crowdkit/aggregation/classification/zero_based_skill.py
=> docs: fix args format

mkdocs.yml
=> docs: improve with symbol show

crowdkit/aggregation/utils.py, pyproject.toml
=> fix: temporary constrain attrs version to <= 23.2.0 to avoid mypy type checking error

README.md
=> docs: fix cmd

crowdkit/aggregation/classification/dawid_skene.py
=> docs(ds): fix fit return doc

crowdkit/aggregation/utils.py, pyproject.toml
Related to https://github.com/Toloka/crowd-kit/issues/121#issuecomment-2322213406
=> deps(attrs): relaxed requirement to attrs

docs/javascripts/mathjax.js
=> fix: load boldsymbol mathjax extension

crowdkit/aggregation/classification/majority_vote.py, crowdkit/aggregation/classification/zero_based_skill.py, crowdkit/aggregation/multilabel/binary_relevance.py
=> doc: fix format
